# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mongoid_localizable}
  s.version = "0.1.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rodrigo \303\201lvarez"]
  s.date = %q{2010-08-29}
  s.description = %q{This gem aims to be a transparent way to deal with localizable fields.
      Basically use localized_field() instead of field() and that's it.
      It will take care of locales for you when using find or criteria.
      }
  s.email = %q{papipo@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "config/locales/en.yml",
     "lib/mongoid/localizable.rb",
     "lib/mongoid/localizable/localized_criteria.rb",
     "lib/mongoid/localizable/localized_field.rb",
     "lib/mongoid/localizable/localized_validator.rb",
     "mongoid_localizable.gemspec",
     "spec/.rspec",
     "spec/integration/mongoid/localizable_spec.rb",
     "spec/spec_helper.rb",
     "spec/unit/mongoid/localizable/localized_criteria_spec.rb",
     "spec/unit/mongoid/localizable_spec.rb"
  ]
  s.homepage = %q{http://github.com/Papipo/mongoid_i18n}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Mongoid plugin to deal with localizable fields}
  s.test_files = [
    "spec/integration/mongoid/localizable_spec.rb",
     "spec/spec_helper.rb",
     "spec/unit/mongoid/localizable/localized_criteria_spec.rb",
     "spec/unit/mongoid/localizable_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mongoid>, [">= 2.0.0.beta.9"])
      s.add_development_dependency(%q<rspec>, [">= 2.0.0.beta.8"])
    else
      s.add_dependency(%q<mongoid>, [">= 2.0.0.beta.9"])
      s.add_dependency(%q<rspec>, [">= 2.0.0.beta.8"])
    end
  else
    s.add_dependency(%q<mongoid>, [">= 2.0.0.beta.9"])
    s.add_dependency(%q<rspec>, [">= 2.0.0.beta.8"])
  end
end

